action_id: trunk-single-player-auto-upgrade
date: 2024-03-24 15:15:47
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1711293347
full_timestamp:
  nanos: 697108000
  seconds: 1711293347
trunk_version: 1.21.0
