action_id: trunk-single-player-auto-on-upgrade
date: 2024-03-13 19:33:42
run: trunk on-upgrade --single-player-only -n --no-progress --allow-daemon-start=false --print-summary --scope=check,plugins,runtimes,tools
run_from: ""
trigger: schedule 24h+5m
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Trunk Internal Error: Please report this issue at https://slack.trunk.io (reference id: 932a7c35738d424c4e684ed46d6ccc8a)\x1b[0m\r\n"
  err: ""
timestamp: 1710358422
full_timestamp:
  nanos: 609741000
  seconds: 1710358422
trunk_version: 1.20.1
