action_id: trunk-single-player-auto-on-upgrade
date: 2024-03-24 03:49:10
run: trunk on-upgrade --single-player-only -n --no-progress --allow-daemon-start=false --print-summary --scope=check,plugins,runtimes,tools
run_from: ""
trigger: schedule 24h+5m
result:
  exit_code: 0
  out: "\r\n\x1b[1m4 linters were upgraded:\r\n\r\n\x1b[0m  black \x1b[90m24.2.0\x1b[0m → \x1b[92m24.3.0\x1b[0m\r\n  checkov \x1b[90m3.2.38\x1b[0m → \x1b[92m3.2.43\x1b[0m\r\n  ruff \x1b[90m0.3.2\x1b[0m → \x1b[92m0.3.4\x1b[0m\r\n  trufflehog \x1b[90m3.69.0\x1b[0m → \x1b[92m3.70.3\x1b[0m\r\n\r\n\x1b[1m1 plugin was upgraded:\r\n\r\n\x1b[0m  trunk-io/plugins \x1b[90mv1.4.4\x1b[0m → \x1b[92mv1.4.5\x1b[0m\r\n\r\n"
  err: ""
timestamp: 1711252150
full_timestamp:
  nanos: 799755000
  seconds: 1711252150
trunk_version: 1.21.0
