action_id: trunk-single-player-auto-on-upgrade
date: 2024-03-28 15:29:22
run: trunk on-upgrade --single-player-only -n --no-progress --allow-daemon-start=false --print-summary --scope=check,plugins,runtimes,tools
run_from: ""
trigger: schedule 24h+5m
result:
  exit_code: 0
  out: "\r\n\x1b[1m1 linter was upgraded:\r\n\r\n\x1b[0m  checkov \x1b[90m3.2.47\x1b[0m → \x1b[92m3.2.48\x1b[0m\r\n\r\n"
  err: ""
timestamp: 1711639762
full_timestamp:
  nanos: 821202000
  seconds: 1711639762
trunk_version: 1.21.0
