@echo off
REM Generated by trunk tool 'black'
set HOME=%HOME%
if not defined HOME set HOME=
set VIRTUAL_ENV=C:\Users\Admin\AppData\Local\trunk\tools\black\24.3.0-44dda8e988ffcce5fe8f38528db3707f
set PATH=C:\Users\Admin\AppData\Local\trunk\tools\black\24.3.0-44dda8e988ffcce5fe8f38528db3707f/bin;C:\Users\Admin\AppData\Local\trunk\tools\black\24.3.0-44dda8e988ffcce5fe8f38528db3707f/Scripts;C:\Users\Admin\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\Admin\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\Admin\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Admin\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set PYTHONUTF8=1

start /w /b black %*
