@echo off
REM Generated by trunk tool 'ruff'
set PATH=C:\Users\Admin\AppData\Local\trunk\tools\ruff\0.3.4-ed52c6c6a22e9545186f527d6118988e/bin;C:\Users\Admin\AppData\Local\trunk\tools\ruff\0.3.4-ed52c6c6a22e9545186f527d6118988e/Scripts;C:\Users\Admin\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\Admin\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\Admin\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Admin\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set HOME=%HOME%
if not defined HOME set HOME=
set PYTHONUTF8=1
set VIRTUAL_ENV=C:\Users\Admin\AppData\Local\trunk\tools\ruff\0.3.4-ed52c6c6a22e9545186f527d6118988e

start /w /b ruff %*
