@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\Admin\AppData\Local\trunk\tools\trufflehog\3.71.0-ed95a093eb2afa1e2f4960672f14b994;C:\Users\Admin\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Admin\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
