action_id: trunk-whoami
date: 2024-03-27 15:33:52
run: trunk whoami
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1711553632
full_timestamp:
  nanos: 508286000
  seconds: 1711553632
trunk_version: 1.21.0
