action_id: trunk-whoami
date: 2024-03-29 14:04:55
run: trunk whoami
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Not logged in. Run \"trunk login\" to login\x1b[0m\r\n"
  err: ""
timestamp: 1711721095
full_timestamp:
  nanos: 482152000
  seconds: 1711721095
trunk_version: 1.21.0
