action_id: trunk-upgrade-available
date: 2024-03-17 01:11:25
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: .trunk/trunk.yaml
result:
  exit_code: 0
  out: "notifications:\r\n  - commands:\r\n      - run: trunk upgrade\r\n        title: all\r\n      - run: trunk upgrade check\r\n        title: Linters\r\n    id: trunk-upgrade\r\n    message: \" 1 linter upgrade\\n\"\r\n    priority: low\r\n    rendered: \"\\x1b[90mRun \\x1b[0m\\x1b[96mtrunk upgrade\\x1b[0m\\x1b[90m to upgrade \\x1b[0m\\x1b[90m1 linter\\n\\x1b[0m\"\r\n    title: Upgrade Available\r\nnotifications_to_delete:\r\n  - trunk-check-upgrade\r\n"
  err: ""
timestamp: 1710637885
full_timestamp:
  nanos: 770085000
  seconds: 1710637885
trunk_version: 1.21.0
action_output:
  notifications:
    - commands:
        - run: trunk upgrade
          title: all
        - run: trunk upgrade check
          title: Linters
      full_timestamp:
        nanos: 770085000
        seconds: 1710637885
      id: trunk-upgrade
      message: " 1 linter upgrade\n"
      priority: low
      rendered: "\x1b[90mRun \x1b[0m\x1b[96mtrunk upgrade\x1b[0m\x1b[90m to upgrade \x1b[0m\x1b[90m1 linter\n\x1b[0m"
      timestamp: 1710637885
      title: Upgrade Available
  notifications_to_delete:
    - trunk-check-upgrade
