action_id: trunk-upgrade-available
date: 2024-03-27 15:54:12
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1711554852
full_timestamp:
  nanos: 389528000
  seconds: 1711554852
trunk_version: 1.21.0
