action_id: trunk-upgrade-available
date: 2024-03-04 18:51:34
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1709578294
full_timestamp:
  nanos: 36429000
  seconds: 1709578294
trunk_version: 1.20.1
