action_id: trunk-share-with-everyone
date: 2024-03-29 14:04:55
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-share-with-everyone\r\n"
  err: ""
timestamp: 1711721095
full_timestamp:
  nanos: 450626000
  seconds: 1711721095
trunk_version: 1.21.0
action_output:
  notifications_to_delete:
    - trunk-share-with-everyone
